---
- hosts: kubernetes
  gather_facts: false

  pre_tasks:
    - name: status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
      
    - name: version.
      command: minikube version

    - name: Start.
      command: minikube start
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"

    # Create Kubernetes resources to run flask app.
    - name: Create a Deployment for flask app.
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: flask-saran-deployment
            namespace: default
            labels:
              app: flask
          spec:
            selector:
              matchLabels:
                app: flask
            replicas: 3 # tells deployment to run 3 pods matching the template
            template:
              metadata:
                labels:
                  app: flask
              spec:
                containers:
                - name: flask
                  image: sarankaja/kubesba
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 80    
            strategy:
              type: RollingUpdate
              rollingUpdate:
                maxSurge: 1
                maxUnavailable: 0

    - name: Create a Service for flask app.
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: flask-saran-service
            namespace: default
          spec:
            type: NodePort
            selector:
              app: flask
            ports:
            - protocol: TCP
              port: 80
              targetPort: 80
  
